Nop.Plugin.Misc.ProductNameModifier/Models/ConfigurationModel.cs
using Nop.Core.Configuration;

namespace Nop.Plugin.Misc.ProductNameModifier.Models
{
    /// <summary>
    /// Represents configuration model for product name modifier
    /// </summary>
    public class ConfigurationModel
    {
        /// <summary>
        /// Gets or sets a value indicating whether to enable the plugin
        /// </summary>
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or sets the prefix to add to product names
        /// </summary>
        public string Prefix { get; set; }

        /// <summary>
        /// Gets or sets the suffix to add to product names
        /// </summary>
        public string Suffix { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether to apply to all products
        /// </summary>
        public bool ApplyToAllProducts { get; set; }
    }
}

Nop.Plugin.Misc.ProductNameModifier/Controllers/ProductNameModifierController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Misc.ProductNameModifier.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System.Threading.Tasks;

namespace Nop.Plugin.Misc.ProductNameModifier.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class ProductNameModifierController : BasePluginController
    {
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;

        public ProductNameModifierController(
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
        }

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
                return AccessDeniedView();

            var settings = await _settingService.LoadSettingAsync<ProductNameModifierSettings>();
            var model = new ConfigurationModel
            {
                Enabled = settings.Enabled,
                Prefix = settings.Prefix,
                Suffix = settings.Suffix,
                ApplyToAllProducts = settings.ApplyToAllProducts
            };

            return View("~/Plugins/Misc.ProductNameModifier/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePlugins))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            var settings = await _settingService.LoadSettingAsync<ProductNameModifierSettings>();
            settings.Enabled = model.Enabled;
            settings.Prefix = model.Prefix ?? string.Empty;
            settings.Suffix = model.Suffix ?? string.Empty;
            settings.ApplyToAllProducts = model.ApplyToAllProducts;

            await _settingService.SaveSettingAsync(settings);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }
    }
}

Nop.Plugin.Misc.ProductNameModifier/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}
@model Nop.Plugin.Misc.ProductNameModifier.Models.ConfigurationModel

<form asp-controller="ProductNameModifier" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="Enabled" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Enabled" />
                        <span asp-validation-for="Enabled"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="Prefix" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Prefix" />
                        <span asp-validation-for="Prefix"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="Suffix" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Suffix" />
                        <span asp-validation-for="Suffix"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="ApplyToAllProducts" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ApplyToAllProducts" />
                        <span asp-validation-for="ApplyToAllProducts"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" name="save" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>